# Copyright © 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

name: OpenIM Dependency Review
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check Dependency graph and GitHub Advanced Security'
        id: check_dependencies
        run: |
          # Custom script or action to verify if Dependency graph and GitHub Advanced Security are enabled
          # This is a placeholder for the actual script or action
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        if: steps.check_dependencies.outputs.enabled == 'true'
        uses: actions/dependency-review-action@v3